apiVersion: v1
kind: Service
metadata:
  name: {{ include "rancher-telemetry-server.fullname" . }}
  labels:
    {{- include "rancher-telemetry-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: receiver
      protocol: TCP
      name: receiver
  selector:
    {{- include "rancher-telemetry-server.selectorLabels" . | nindent 4 }}
